config/routes.rb
WebTechAssignment4::Application.routes.draw do
  root 'home#index'

  resources :bands do 
  	get :search_names, :on => :collection
    post :search_names, :on => :collection
    get :search_genres, :on => :collection
    post :search_genres, :on => :collection
    get :search_albums, :on => :collection
    post :search_albums, :on => :collection
  end

  resources :genres
  resources :artists
  resources :locations
  resources :shows
  resources :albums
  resources :songs, only: [:destroy, :index]
end

app/models/genre.rb
class Genre < ActiveRecord::Base
	has_many :related_genres, :foreign_key => 'related_genre_id', :class_name => 'Genre'
  	belongs_to :related_to, :class_name => 'Genre'
  	has_many :bands

  	validates :title, uniqueness: true
  	validates :title, presence: true

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

	before_filter :load_genre, only: [:show, :update, :edit, :destroy]

	def show
	end

	def destroy
		@genre.destroy
		writeToXML
		redirect_to bands_path
	end

	def edit
	end

	def update
		@genre.update_attributes(params.require(:genre).permit(:title, :description))
		writeToXML
		redirect_to genre_path(@genre)
	end

	def new
		@genre = Genre.new
	end

	def create
		@genre = Genre.create(params.require(:genre).permit(:title, :description))
		writeToXML
		redirect_to genre_path(@genre)
	end

	def index 
		@genres = Genre.all.order('title')
	end

	def load_genre
		@genre = Genre.find(params[:id])
	end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_genre_new_edit.html.erb
<div>
  <%= render partial: 'common/application_header' %>
  <%= form_for @genre, html: {class: 'form form-horizontal'} do |f| %>
    <fieldset>
      <div>
        <%= f.label :title %>
        <div>
          <%= f.text_field :title %>
        </div>
      </div>
      <div>
        <%= f.label :description %>
        <div>
          <%= f.text_area :description, rows: 5 %>
        </div>
      </div>
      
    <fieldset>
      <%= f.submit edit ? "Update Genre" : "Create Genre", class: "btn btn-primary" %> <%= link_to "Cancel", bands_path %>
    </fieldset>
      
  <% end %>
</div>

app/views/genres/edit.html.erb
<%= render partial: 'genre_new_edit', locals: { genre: @genre, edit: true } %>

app/views/genres/index.html.erb
<div class="padded">
	<%= render partial: 'common/application_header' %>
	<div class="container">
		<h2 class="title centered">Genres</h2>
		<p class="centered"><%= link_to "Add New Genre", new_genre_path %></p>
		<% @genres.each do |genre| %>
			<p><%= link_to genre.title, genre_path(genre) %></p>
		<% end %>
	</div>
</div>

app/views/genres/new.html.erb
<%= render partial: 'genre_new_edit', locals: { genre: @genre, edit: false } %>

app/views/genres/show.html.erb
<div class="padded">
	<%= render partial: 'common/application_header' %>
	<div class="container">
		<h2 class="title centered"><%= @genre.title %></h1>
		<p class="centered">
			<%= link_to "Edit", edit_genre_path(@genre) %>
			<% if @genre.bands.count == 0 %>
				 / <%= link_to "Delete", genre_path(@genre), method: :delete, data: { confirm: 'Are you sure you want to delete this genre?' } %>
			<% end %>
		</p>
		<b>Description: </b><%= @genre.description %>
		<% if @genre.bands.count > 0 %>
			<p><b>Bands in this genre: </b></p>
			<ul>
				<% @genre.bands.each do |band| %>
					<li><%= link_to band.name, band_path(band) %></li>
				<% end %>
			</ul>
		<% end %>
	</div>
</div>