config/routes.rb
WebTechAssignment4::Application.routes.draw do
  root 'home#index'

  resources :bands do 
  	get :search_names, :on => :collection
    post :search_names, :on => :collection
    get :search_genres, :on => :collection
    post :search_genres, :on => :collection
    get :search_albums, :on => :collection
    post :search_albums, :on => :collection
  end

  resources :genres
  resources :artists
  resources :locations
  resources :shows
  resources :albums
  resources :songs, only: [:destroy, :index]
end

app/models/artist.rb
class Artist < ActiveRecord::Base
	belongs_to :band

	validates :name, uniqueness: true
	validates :name, :role, presence: true
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
	before_filter :load_artist, only: [:show, :update, :edit, :destroy]

	def show
	end

	def destroy
		band = @artist.band
		@artist.destroy
		writeToXML
		case params[:from]
		when "edit_band"
			redirect_to edit_band_path(band)
		when nil
			redirect_to bands_path
		end
	end

	def edit
		@bands = Band.all
	end

	def update
		@artist.update_attributes(params.require(:artist).permit(:name, :biography, :birthday, :role, :join_date, :band_id))
		writeToXML
		redirect_to artist_path(@artist)
	end

	def create
		@artist = Artist.create(params.require(:artist).permit(:name, :biography, :birthday, :role, :join_date, :band_id))
		writeToXML
		redirect_to edit_band_path(@artist.band)
	end

	def new
		@artist = Artist.new
		@artist.band_id = Band.find(params[:band_id]).id if params[:band_id].present?
		@bands = Band.all
	end

	def index
		@artists = Artist.all.order('name')
	end

	def load_artist
		@artist = Artist.find(params[:id])
	end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_artist_new_edit.html.erb
<div>
  <%= render partial: 'common/application_header' %>
  <%= form_for @artist, html: {class: 'form form-horizontal'} do |f| %>
    <fieldset>
      <div>
        <%= f.label :name %>
        <div>
          <%= f.text_field :name %>
        </div>
      </div>
      <div>
        <%= f.label :biography %>
        <div>
          <%= f.text_area :biography, rows: 5 %>
        </div>
      </div>
      <div>
        <%= f.label :role %>
        <div>
          <%= f.text_field :role, rows: 5 %>
        </div>
      </div>
      <div>
        <%= f.label :birthday %>
        <div>
          <%= f.datetime_select :birthday, { include_blank: true, start_year: 1920, end_year: 2013 } %>
        </div>
      </div>
      <div>
        <%= f.label :join_date %>
        <div>
          <%= f.datetime_select :join_date, { include_blank: true, start_year: 1920, end_year: 2013 } %>
        </div>
      </div>
      <div>
        <%= f.label "Band: " %> <%= f.collection_select(:band_id, @bands, :id, :name) %>
      </div>
      
    <fieldset>
      <%= f.submit edit ? "Edit Artist" : "Add Artist", class: "btn btn-primary" %> <%= link_to "Cancel", bands_path %>
    </fieldset>
  <% end %>
</div>

app/views/artists/edit.html.erb
<%= render partial: 'artist_new_edit', locals: { artist: @artist, edit: true, bands: @bands } %>

app/views/artists/index.html.erb
<div class="padded">
	<%= render partial: 'common/application_header' %>
	<div class="container">
		<h2 class="title centered">Artists</h2>
		<p class="centered"><%= link_to "Add New Artist", new_artist_path %></p>
		<% @artists.each do |artist| %>
			<p><%= link_to artist.name, artist_path(artist) %></p>
		<% end %>
	</div>
</div>

app/views/artists/new.html.erb
<%= render partial: 'artist_new_edit', locals: { artist: @artist, edit: false, bands: @bands } %>

app/views/artists/show.html.erb
<div class="padded">
	<%= render partial: 'common/application_header' %>
	<div class="container">
		<h2 class="title centered"><%= @artist.name %></h1>
		<p class="centered">
			<%= link_to "Edit", edit_artist_path(@artist) %> / <%= link_to "Delete", artist_path(@artist), method: :delete, data: { confirm: 'Are you sure you want to delete this artist?' } %>
		</p>
		<p>
			<b>Band: </b><%= link_to @artist.band.name, band_path(@artist.band) %>
		</p>
		<p>
			<b>Role: </b><%= @artist.role %>
		</p>
		<p>
			<b>Biography: </b><%= @artist.biography %>
		</p>
		<p>
			<b>Birthday: </b><%= @artist.birthday.strftime("%B %d, %Y") if @artist.birthday.present? %>
		</p>
		<p>
			<b>Joined date: </b><%= @artist.join_date.strftime("%B %d, %Y") if @artist.join_date.present? %>
		</p>
	</div>
</div>