config/routes.rb
WebTechAssignment4::Application.routes.draw do
  root 'home#index'

  resources :bands do 
  	get :search_names, :on => :collection
    post :search_names, :on => :collection
    get :search_genres, :on => :collection
    post :search_genres, :on => :collection
    get :search_albums, :on => :collection
    post :search_albums, :on => :collection
  end

  resources :genres
  resources :artists
  resources :locations
  resources :shows
  resources :albums
  resources :songs, only: [:destroy, :index]
end

app/models/album.rb
class Album < ActiveRecord::Base
	belongs_to :band
	has_many :songs, inverse_of: :album, dependent: :destroy

	validates :title, uniqueness: true
	validates :title, presence: true

	accepts_nested_attributes_for :songs, reject_if: proc { |attributes| attributes['title'].blank? }, allow_destroy: true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
	before_filter :load_album, only: [:show, :update, :edit, :destroy]

	def show
	end

	def destroy
		band = @album.band
		@album.destroy
		writeToXML
		case params[:from]
		when "edit_band"
			redirect_to edit_band_path(band)
		when nil
			redirect_to bands_path
		end
	end

	def edit
		@bands = Band.all
		@new_album = Album.new
	end

	def update
		@album.update_attributes(params.require(:album).permit(:title, :release_date, :band_id, songs_attributes: [ :id, :title, :ranking ]))
		writeToXML
		redirect_to album_path(@album)
	end

	def new
		@album = Album.new
		@new_album = Album.new
		@bands = Band.all
		@album.band_id = Band.find(params[:band_id]).id if params[:band_id].present?
	end

	def create
		@album = Album.create(params.require(:album).permit(:title, :release_date, :band_id, songs_attributes: [ :id, :title, :ranking ]))
		writeToXML
		redirect_to edit_band_path(@album.band)
	end

	def index
		@albums = Album.all.order('title')
	end

	def load_album
		@album = Album.find(params[:id])
	end
end

app/helpers/albums_helper.rb
module AlbumsHelper
	def add_song(album)
		album.songs << Song.new
	end
end

app/views/albums/_album_new_edit.html.erb
<div>
  <%= render partial: 'common/application_header' %>
  <%= form_for @album, html: {class: 'form form-horizontal'} do |f| %>
    <fieldset>
      <div>
        <%= f.label :title%>
        <div>
          <%= f.text_field :title %>
        </div>
      </div>
      <div>
        <%= f.label "Band"%>
        <div>
          <%= f.collection_select(:band_id, @bands, :id, :name) %><%= link_to "Add new band", new_band_path %>
        </div>
      </div>
      <div>
        <%= f.label :release_date %>
        <div>
          <%= f.datetime_select :release_date, { include_blank: true, start_year: 1920, end_year: 2013 } %>
        </div>
      </div>
      <h4>Songs</h4>
      <div class="songs">
      <%= f.fields_for :songs, @album.songs do |q| %>
        <div class="song">
          <div>
            <%= q.label :title %>: 
            <%= q.text_field :title %> 
            <%= q.label :ranking %>: 
            <%= q.text_field :ranking %>
            <%= link_to "Delete", song_path(q.object), method: :delete, data: { confirm: 'Are you sure you want to delete this song?' } %>
          </div>
        </div>
      <% end %>
    </div>
    <a href="javascript:void(0)" id="new-song">Add new song</a>
      
    <fieldset>
      <%= f.submit edit ? "Update Album" : "Create Album", class: "btn btn-primary" %> <%= link_to "Cancel", bands_path %>
    </fieldset>
  <% end %>
</div>

<div class="hidden">
  <% add_song(@new_album) %>
  <%= form_for @new_album do |f| %>
    <%= f.fields_for :songs do |q| %>
      <div id='song-template'>
        <div>
          <%= q.label :title %>: 
          <%= q.text_field :title %> 
          <%= q.label :ranking %>: 
          <%= q.text_field :ranking %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/albums/edit.html.erb
<%= render partial: 'album_new_edit', locals: { album: @album, edit: true, genres: @genres, locations: @locations } %>

app/views/albums/index.html.erb
<div class="padded">
	<%= render partial: 'common/application_header' %>
	<div class="container">
		<h2 class="title centered">Albums</h2>
		<p class="centered"><%= link_to "Add New Album", new_album_path %></p>
		<% @albums.each do |album| %>
			<p><%= link_to album.title, album_path(album) %></p>
		<% end %>
	</div>
</div>

app/views/albums/new.html.erb
<%= render partial: 'album_new_edit', locals: { album: @album, edit: false, genres: @genres, locations: @locations } %>

app/views/albums/show.html.erb
<div class="padded">
	<%= render partial: 'common/application_header' %>
	<div class="container">
		<h2 class="title centered"><%= @album.title %></h2>
		<p class="centered">
			<%= link_to "Edit", edit_album_path(@album) %> / 
			<%= link_to "Delete", album_path(@album), method: :delete, data: { confirm: 'Are you sure you want to delete this album?' } %>
		</p>
		<div class="top-margined">
			<b>Title: </b><%= @album.title %>
		</div>
		<div class="top-margined">
			<b>Release Date: </b><%= @album.release_date.strftime("%B %d, %Y") if @album.release_date.present? %>
		</div>
		<div class="top-margined">
			<b>Band: </b><%= @album.band.name %>
		</div>
		<b><u>Songs:</u></b>
		<ul>
			<% @album.songs.each do |song| %>
				<li>
					<%= song.title %>
					<% if song.ranking.present? %>
						<%= ", ranking: #{song.ranking}" %>
					<% end %>
				</li>
			<% end %>
		</ul>
	</div>
</div>