config/routes.rb
WebTechAssignment4::Application.routes.draw do
  root 'home#index'

  resources :bands do 
  	get :search_names, :on => :collection
    post :search_names, :on => :collection
    get :search_genres, :on => :collection
    post :search_genres, :on => :collection
    get :search_albums, :on => :collection
    post :search_albums, :on => :collection
  end

  resources :genres
  resources :artists
  resources :locations
  resources :shows
  resources :albums
  resources :songs, only: [:destroy, :index]
end

app/models/band.rb
class Band < ActiveRecord::Base
	belongs_to :genre
	has_many :artists, dependent: :destroy
	has_many :albums, dependent: :destroy
	has_many :shows, dependent: :destroy

	validates :name, uniqueness: true, presence: true

	accepts_nested_attributes_for :shows, reject_if: proc { |attributes| attributes['title'].blank? }, allow_destroy: true
	accepts_nested_attributes_for :artists, reject_if: proc { |attributes| attributes['name'].blank? }, allow_destroy: true
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
	before_filter :load_band, only: [:show, :update, :edit, :destroy]

  def index
    @bands = Band.paginate(:page => params[:page], :per_page => 2).order('name')
    @genres = Genre.all
    @albums = Album.all
  end

  def show
  end

  def edit
  	@genres = Genre.all
    @locations = Location.all
  	@new_band = Band.new
  end

  def update
  	@band.update_attributes(params.require(:band).permit(:name, :description, :genre_id, artists_attributes: [ :id, :name, :biography, :role, :birthday, :join_date, :_destroy ], shows_attributes: [ :id, :title, :date, :venue, :location_id, :_destroy ]))
    writeToXML
	  redirect_to band_path(@band)
  end

  def destroy
  	@band.destroy
    writeToXML
  	redirect_to bands_path
  end

  def new
    @band = Band.new
    @new_band = Band.new
    @genres = Genre.all
    @locations = Location.all
  end

  def create
    @genre = Band.create(params.require(:band).permit(:name, :description, :genre_id, artists_attributes: [ :id, :name, :biography, :role, :birthday, :join_date, :_destroy ], shows_attributes: [ :id, :title, :date, :venue, :location_id, :_destroy ]))
    writeToXML
    redirect_to band_path(@genre)
  end

  def load_band
  	@band = Band.find(params[:id])
  end

  def search_names
    band = Band.find_by_name(params[:name])
    if band.present? 
      redirect_to band_path(band)
    else 
      @name = params[:name]
    end
  end

  def search_genres
    @bands = Band.where(genre_id: params[:genre_id])
    @genre = Genre.find(params[:genre_id]).title
    if @bands.empty?
      @found = false
    else
      @found = true
    end
  end

  def search_albums
    album = Album.find(params[:album_id])
    band = Band.find(album.band_id)
    if band.present? 
      redirect_to band_path(band)
    else 
      @album = album.name
    end
  end
end

app/helpers/bands_helper.rb
module BandsHelper
	def add_artist(band)
		band.artists << Artist.new
	end

	def add_show(band)
		band.shows << Show.new
	end
end

app/views/bands/_band_new_edit.html.erb
<div>
  <%= render partial: 'common/application_header' %>
  <%= form_for @band, html: {class: 'form form-horizontal'} do |f| %>
    <fieldset>
      <div>
        <%= f.label :name %>
        <div>
          <%= f.text_field :name %>
        </div>
      </div>
      <div>
        <%= f.label :description %>
        <div>
          <%= f.text_area :description, rows: 5 %>
        </div>
      </div>
      <div>
        <%= f.label :genre %>
        <div>
          <%= f.collection_select(:genre_id, @genres, :id, :title) %><%= link_to "Add new genre", new_genre_path %>
        </div>
      </div>

      <h4>Members</h4>
      <div class="members">
        <%= f.fields_for :artists, @band.artists do |q| %>
          <div>
            <%= q.object.name %>  
            <a href="javascript:void(0)" class="edit-artist" member-id=<%= q.object.id %>>Edit</a> / 
            <%= link_to "Delete", artist_path(q.object, from: "edit_band"), method: :delete, data: { confirm: 'Are you sure you want to delete this artist?' } %>
          </div>
          <div class="member toggle-visibility" data-id= <%= q.object.id %> >
            <fieldset>
              <div>
                <%= q.label :name %>
                <div>
                  <%= q.text_field :name %>
                </div>
              </div>
              <div>
                <%= q.label :biography %>
                <div>
                  <%= q.text_area :biography, rows: 5 %>
                </div>
              </div>
              <div>
                <%= q.label :role %>
                <div>
                  <%= q.text_field :role, rows: 5 %>
                </div>
              </div>
              <div>
                <%= q.label :birthday %>
                <div>
                  <%= q.datetime_select :birthday, { include_blank: true, start_year: 1920, end_year: 2013 } %>
                </div>
              </div>
              <div>
                <%= q.label :join_date %>
                <div>
                  <%= q.datetime_select :join_date, { include_blank: true, start_year: 1920, end_year: 2013 } %>
                </div>
              </div>
              <a href="javascript:void(0)" class="done-editing-artist" member-id=<%= q.object.id %>>Done Editing</a>
              
            </fieldset>
          </div>
        <% end %>
      </div>
      <div>
        <a href="javascript:void(0)" id="new-artist">Add Member</a>
      </div>

      <h4>Albums</h4>
      <% @band.albums.each do |album| %>
          <div>
            <%= album.title %>  <%= link_to "Edit", edit_album_path(album) %> / <%= link_to "Delete", album_path(album, from: "edit_band"), method: :delete, data: { confirm: 'Are you sure you want to delete this album?' } %>
          </div>
      <% end %>
      <div>
        <%= link_to "Add album", new_album_path(band_id: @band.id) %>
      </div>

      <h4>Shows</h4>
      <div class="shows">
        <%= f.fields_for :shows, @band.shows do |q| %>
          <div>
            <%= q.object.title %>  
            <a href="javascript:void(0)" class="edit-show" show-id=<%= q.object.id %>>Edit</a> / 
            <%= link_to "Delete", show_path(q.object, from: "edit_band"), method: :delete, data: { confirm: 'Are you sure you want to delete this show?' } %>
          </div>
          <div class="show toggle-visibility" data-id= <%= q.object.id %>>
            <fieldset>
              <div>
                <%= q.label :title %>
                <div>
                  <%= q.text_field :title %>
                </div>
              </div>
              <div>
                <%= q.label :date %>
                <div>
                  <%= q.datetime_select :date, { include_blank: true, start_year: 1920, end_year: 2013 } %>
                </div>
              </div>
              <div>
                <%= q.label :venue %>
                <div>
                  <%= q.collection_select(:location_id, @locations, :id, :venue) %><%= link_to "Add new location", new_location_path %>
                </div>
              </div>
              <a href="javascript:void(0)" class="done-editing-show" show-id=<%= q.object.id %>>Done Editing</a>
            <fieldset>
          </div>
        <% end %>
      </div>
      <div>
        <a href="javascript:void(0)" id="new-show">Add Show</a>
      </div>
              
    <%= f.submit edit ? "Update Band" : "Create Band" %> <%= link_to "Cancel", bands_path %>
    </fieldset>
  <% end %>
</div>

<div class="hidden">
  <% add_artist(@new_band) %>
  <% add_show(@new_band) %>
  <%= form_for @new_band do |f| %>
    <%= f.fields_for :artists do |q| %>
      <div id='artist-template'>
        <div>
          <fieldset>
              <div>
                <%= q.label :name %>
                <div>
                  <%= q.text_field :name %>
                </div>
              </div>
              <div>
                <%= q.label :biography %>
                <div>
                  <%= q.text_area :biography, rows: 5 %>
                </div>
              </div>
              <div>
                <%= q.label :role %>
                <div>
                  <%= q.text_field :role, rows: 5 %>
                </div>
              </div>
              <div>
                <%= q.label :birthday %>
                <div>
                  <%= q.datetime_select :birthday, { include_blank: true, start_year: 1920, end_year: 2013 } %>
                </div>
              </div>
              <div>
                <%= q.label :join_date %>
                <div>
                  <%= q.datetime_select :join_date, { include_blank: true, start_year: 1920, end_year: 2013 } %>
                </div>
              </div>
              
            </fieldset>
        </div>
      </div>
    <% end %>
  <% end %>

  <%= form_for @new_band do |f| %>
    <%= f.fields_for :shows do |q| %>
      <div id='show-template'>
        <div>
          <fieldset>
              <div>
                <%= q.label :title %>
                <div>
                  <%= q.text_field :title %>
                </div>
              </div>
              <div>
                <%= q.label :date %>
                <div>
                  <%= q.datetime_select :date, { include_blank: true, start_year: 1920, end_year: 2013 } %>
                </div>
              </div>
              <div>
                <%= q.label :venue %>
                <div>
                  <%= q.collection_select(:location_id, @locations, :id, :venue) %><%= link_to "Add new location", new_location_path %>
                </div>
              </div>
              
            <fieldset>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/bands/edit.html.erb
<%= render partial: 'band_new_edit', locals: { band: @bands, edit: true, genres: @genres, locations: @locations } %>

app/views/bands/index.html.erb
<div class="padded">
	<%= render partial: 'common/application_header' %>
	<div class="container">
		<h2 class="title centered">Bands</h1>
		<p class="centered"><%= link_to "Add New Band", new_band_path %></p>

		<!-- inline display not happening -->
		<ul class="search-list centered">
			<li>
				<%= form_tag search_names_bands_path, class: 'form-search' do %>
	        		<%= text_field_tag :name, params[:name], class: 'span2', placeholder: 'Search by Name' %>
	    		<% end %>
	   		</li>
	   		<li>
	    		<%= form_tag search_genres_bands_path, class: 'form-search' do %>
	        		<%= label_tag "Search by Genre", "Search by Genre" %>
	        		<%= select_tag "genre_id", options_from_collection_for_select(@genres, :id, :title )%>
	        		<%= submit_tag "Search" %>
	    		<% end %>
	    	</li>
	   		<li>
	    		<%= form_tag search_albums_bands_path, class: 'form-search' do %>
	        		<%= label_tag "Search by Album", "Search by Album" %>
	        		<%= select_tag "album_id", options_from_collection_for_select(@albums, :id, :title )%>
	        		<%= submit_tag "Search" %>
	    		<% end %>
	    	</li>
	    </ul>

	    <span class="centered"><%= will_paginate @bands %></span>
		<% @bands.each do |band| %>
			<div class="container2">
				<h2 class="title centered"><%= link_to band.name, band_path(band) %></h2>
				<div class="top-margined">
					<b>Genre: </b><%= link_to band.genre.title, genre_path(band.genre) %>
				</div>
				<% if band.description.present? %>
					<div class="top-margined" >
						<b>Description: </b><%= band.description %>
					</div>
				<% end %>
				<div class="top-margined">
					<b>Members: </b>
					<% band.artists.each do |artist| %>
						<%= link_to artist.name, artist_path(artist) %>
					<% end %>
				</div>
				<div class="top-margined">
					<b>Albums: </b>
					<% band.albums.each do |album| %>
						<%= link_to album.title, album_path(album) %>
					<% end %>
				</div>
				<div class="top-margined">
					<b>Shows: </b>
					<% band.shows.each do |show| %>
						<%= link_to show.title, show_path(show) %>
					<% end %>
				</div>
			</div>
			<br><br><br>
		<% end %>
	</div>
</div>

app/views/bands/new.html.erb
<%= render partial: 'band_new_edit', locals: { band: @bands, edit: false, genres: @genres, locations: @locations } %>

app/views/bands/search_genres.html.erb
<div class="padded">
	<%= render partial: 'common/application_header' %>
	<% if @found %>
		<div class="container">
			<% @bands.each do |band| %>
				<div class="container2">
					<h2 class="title"><%= link_to band.name, band_path(band) %></h2>
					<div class="top-margined">
						<b>Genre: </b><%= link_to band.genre.title, genre_path(band.genre) %>
					</div>
					<% if band.description.present? %>
						<div class="top-margined" >
							<b>Description: </b><%= band.description %>
						</div>
					<% end %>
					<div class="top-margined">
						<b>Members: </b>
						<% band.artists.each do |artist| %>
							<%= link_to artist.name, artist_path(artist) %>
						<% end %>
					</div>
					<div class="top-margined">
						<b>Albums: </b>
						<% band.albums.each do |album| %>
							<%= link_to album.title, album_path(album) %>
						<% end %>
					</div>
					<div class=top-margined>
						<b>Shows: </b>
						<% band.shows.each do |show| %>
							<%= link_to show.title, show_path(show) %>
						<% end %>
					</div>
				</div>
				<br><br><br>
			<% end %>
		</div>
	<% else %>
		<div class="container">
			No band matched your search filter of genre: <%= @genre %>
		</div>
	<% end %>
</div>

app/views/bands/search_names.html.erb
<div class="padded">
	<%= render partial: 'common/application_header' %>
	<div class="container">
		No band matched your search filter of <%= @name %>
	</div>
</div>

app/views/bands/show.html.erb
<div class="padded">
	<%= render partial: 'common/application_header' %>
	<div class="container">
		<h2 class="title centered"><%= @band.name %></h2>
		<p class="centered">
			<%= link_to "Edit", edit_band_path(@band) %> / 
			<%= link_to "Delete", band_path(@band), method: :delete, data: { confirm: 'Are you sure you want to delete this band?' } %>
		</p>
		<div class="top-margined">
			<b>Genre: </b><%= link_to @band.genre.title, genre_path(@band.genre) %>
		</div>
		<% if @band.description.present? %>
			<div class="top-margined">
				<b>Description: </b><%= @band.description %>
			</div>
		<% end %>
		<div class="top-margined">
			<b>Members: </b>
			<% @band.artists.each do |artist| %>
				<%= link_to artist.name, artist_path(artist) %>
			<% end %>
		</div>
		<div class="top-margined">
			<b>Albums: </b>
			<% @band.albums.each do |album| %>
				<%= link_to album.title, album_path(album) %>
			<% end %>
		</div>
		<div class="top-margined">
			<b>Shows: </b>
			<% @band.shows.each do |show| %>
				<%= link_to show.title, show_path(show) %>
			<% end %>
		</div>
	</div>
</div>